import { pool } from '../config/db.js';
import { ApiError } from '../utils/ApiError.js';
import { withTransaction } from '../utils/db.js';
import { createReferenceNumber } from '../utils/refNumber.js';

const tableMap = { categories: 'categories', warehouses: 'warehouses' };
function mapRow(row) { return row; }
function duplicate(error, message) { if (error.code === '23505') throw new ApiError(409, message); throw error; }

export async function listCategories() { return (await pool.query('SELECT id, name, created_at, updated_at FROM categories ORDER BY name')).rows.map(mapRow); }
export async function createCategory({ name }) { try { return (await pool.query('INSERT INTO categories (name) VALUES ($1) RETURNING *', [name])).rows[0]; } catch (error) { duplicate(error, 'Category name already exists'); } }
export async function updateCategory(id, data) { try { const result = await pool.query('UPDATE categories SET name = $1, updated_at = NOW() WHERE id = $2 RETURNING *', [data.name, id]); if (!result.rows[0]) throw new ApiError(404, 'Category not found'); return result.rows[0]; } catch (error) { duplicate(error, 'Category name already exists'); } }
export async function deleteCategory(id) { try { const result = await pool.query('DELETE FROM categories WHERE id = $1 RETURNING id', [id]); if (!result.rows[0]) throw new ApiError(404, 'Category not found'); return { id }; } catch (error) { if (error.code === '23503') throw new ApiError(409, 'Category is still in use'); throw error; } }

export async function listProducts(query) { const params = []; const conditions = []; if (query.search) { params.push(`%${query.search}%`); conditions.push(`(p.name ILIKE $${params.length} OR p.sku ILIKE $${params.length})`); } if (query.categoryId) { params.push(query.categoryId); conditions.push(`p.category_id = $${params.length}`); } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; return (await pool.query(`SELECT p.*, c.name AS category_name FROM products p JOIN categories c ON c.id = p.category_id ${where} ORDER BY p.name`, params)).rows; }
export async function getProduct(id) { const result = await pool.query('SELECT p.*, c.name AS category_name FROM products p JOIN categories c ON c.id = p.category_id WHERE p.id = $1', [id]); if (!result.rows[0]) throw new ApiError(404, 'Product not found'); return result.rows[0]; }
export async function getProductStock(id) { await getProduct(id); return (await pool.query('SELECT ps.*, l.name AS location_name, w.name AS warehouse_name FROM product_stock ps JOIN locations l ON l.id = ps.location_id JOIN warehouses w ON w.id = l.warehouse_id WHERE ps.product_id = $1 ORDER BY w.name, l.name', [id])).rows; }
export async function createProduct(input, userId) { return withTransaction(async client => { try { const product = (await client.query('INSERT INTO products (name, sku, category_id, unit_of_measure) VALUES ($1, $2, $3, $4) RETURNING *', [input.name, input.sku, input.categoryId, input.unitOfMeasure])).rows[0]; if (input.initialStock) { await client.query('INSERT INTO product_stock (product_id, location_id, quantity) VALUES ($1, $2, $3)', [product.id, input.initialStock.locationId, input.initialStock.quantity]); await client.query("INSERT INTO stock_moves (product_id, to_location_id, quantity, move_type, reference_type, reference_id, created_by) VALUES ($1, $2, $3, 'INITIAL', 'PRODUCT', $1, $4)", [product.id, input.initialStock.locationId, input.initialStock.quantity, userId]); } return product; } catch (error) { duplicate(error, 'Product SKU already exists or referenced category/location is invalid'); } }); }
export async function updateProduct(id, data) { try { const fields = Object.keys(data); if (!fields.length) return getProduct(id); const values = fields.map(field => data[field]); const assignments = fields.map((field, index) => `${{ name: 'name', sku: 'sku', categoryId: 'category_id', unitOfMeasure: 'unit_of_measure' }[field]} = $${index + 1}`).join(', '); values.push(id); const result = await pool.query(`UPDATE products SET ${assignments}, updated_at = NOW() WHERE id = $${values.length} RETURNING *`, values); if (!result.rows[0]) throw new ApiError(404, 'Product not found'); return result.rows[0]; } catch (error) { duplicate(error, 'Product update conflicts with an existing record'); } }
export async function deleteProduct(id) { try { const result = await pool.query('DELETE FROM products WHERE id = $1 RETURNING id', [id]); if (!result.rows[0]) throw new ApiError(404, 'Product not found'); return { id }; } catch (error) { if (error.code === '23503') throw new ApiError(409, 'Product is still in use'); throw error; } }

export async function listReorderRules() { return (await pool.query('SELECT rr.*, p.name AS product_name, p.sku FROM reorder_rules rr JOIN products p ON p.id = rr.product_id ORDER BY p.name')).rows; }
export async function createReorderRule(input) { try { if (input.reorderToQty < input.minQty) throw new ApiError(400, 'reorderToQty must be greater than or equal to minQty'); return (await pool.query('INSERT INTO reorder_rules (product_id, min_qty, reorder_to_qty) VALUES ($1, $2, $3) RETURNING *', [input.productId, input.minQty, input.reorderToQty])).rows[0]; } catch (error) { duplicate(error, 'A reorder rule already exists for this product'); } }
export async function deleteReorderRule(id) { const result = await pool.query('DELETE FROM reorder_rules WHERE id = $1 RETURNING id', [id]); if (!result.rows[0]) throw new ApiError(404, 'Reorder rule not found'); return { id }; }
export async function updateReorderRule(id, input) { const fields = []; const values = []; if (input.minQty !== undefined) { values.push(input.minQty); fields.push(`min_qty = $${values.length}`); } if (input.reorderToQty !== undefined) { values.push(input.reorderToQty); fields.push(`reorder_to_qty = $${values.length}`); } if (!fields.length) throw new ApiError(400, 'No fields to update'); values.push(id); const result = await pool.query(`UPDATE reorder_rules SET ${fields.join(', ')}, updated_at = NOW() WHERE id = $${values.length} RETURNING *`, values); if (!result.rows[0]) throw new ApiError(404, 'Reorder rule not found'); if (Number(result.rows[0].reorder_to_qty) < Number(result.rows[0].min_qty)) throw new ApiError(400, 'reorderToQty must be greater than or equal to minQty'); return result.rows[0]; }

export async function listWarehouses() { return (await pool.query('SELECT * FROM warehouses ORDER BY name')).rows; }
export async function createWarehouse(input) { try { return (await pool.query('INSERT INTO warehouses (name, code) VALUES ($1, $2) RETURNING *', [input.name, input.code])).rows[0]; } catch (error) { duplicate(error, 'Warehouse code already exists'); } }
export async function updateWarehouse(id, input) { const fields = []; const values = []; if (input.name !== undefined) { values.push(input.name); fields.push(`name = $${values.length}`); } if (input.code !== undefined) { values.push(input.code); fields.push(`code = $${values.length}`); } if (!fields.length) throw new ApiError(400, 'No fields to update'); values.push(id); try { const result = await pool.query(`UPDATE warehouses SET ${fields.join(', ')}, updated_at = NOW() WHERE id = $${values.length} RETURNING *`, values); if (!result.rows[0]) throw new ApiError(404, 'Warehouse not found'); return result.rows[0]; } catch (error) { duplicate(error, 'Warehouse code already exists'); } }
export async function deleteWarehouse(id) { try { const result = await pool.query('DELETE FROM warehouses WHERE id = $1 RETURNING id', [id]); if (!result.rows[0]) throw new ApiError(404, 'Warehouse not found'); return { id }; } catch (error) { if (error.code === '23503') throw new ApiError(409, 'Warehouse is still in use'); throw error; } }
export async function listLocations(warehouseId) { return (await pool.query('SELECT * FROM locations WHERE warehouse_id = $1 ORDER BY name', [warehouseId])).rows; }
export async function createLocation(input) { try { return (await pool.query('INSERT INTO locations (warehouse_id, name) VALUES ($1, $2) RETURNING *', [input.warehouseId, input.name])).rows[0]; } catch (error) { duplicate(error, 'Location already exists in this warehouse'); } }
export async function updateLocation(id, input) { try { const result = await pool.query('UPDATE locations SET name = $1, updated_at = NOW() WHERE id = $2 RETURNING *', [input.name, id]); if (!result.rows[0]) throw new ApiError(404, 'Location not found'); return result.rows[0]; } catch (error) { duplicate(error, 'Location already exists in this warehouse'); } }
export async function deleteLocation(id) { try { const result = await pool.query('DELETE FROM locations WHERE id = $1 RETURNING id', [id]); if (!result.rows[0]) throw new ApiError(404, 'Location not found'); return { id }; } catch (error) { if (error.code === '23503') throw new ApiError(409, 'Location is still in use'); throw error; } }
