import { Router } from 'express';
import { requireAuth } from '../middleware/auth.middleware.js';
import { validate } from '../middleware/validate.middleware.js';
import * as controller from '../controllers/catalog.controller.js';
import { categorySchema, idParamSchema, locationSchema, locationUpdateSchema, productQuerySchema, productSchema, productUpdateSchema, reorderRuleSchema, reorderRuleUpdateSchema, warehouseSchema, warehouseUpdateSchema } from '../validators/catalog.validators.js';

const router = Router();
router.use(requireAuth);
router.get('/categories', controller.listCategories);
router.post('/categories', validate(categorySchema), controller.createCategory);
router.put('/categories/:id', validate(idParamSchema, 'params'), validate(categorySchema), controller.updateCategory);
router.delete('/categories/:id', validate(idParamSchema, 'params'), controller.deleteCategory);
router.get('/products', validate(productQuerySchema, 'query'), controller.listProducts);
router.post('/products', validate(productSchema), controller.createProduct);
router.get('/products/:id/stock', validate(idParamSchema, 'params'), controller.getProductStock);
router.get('/products/:id', validate(idParamSchema, 'params'), controller.getProduct);
router.put('/products/:id', validate(idParamSchema, 'params'), validate(productUpdateSchema), controller.updateProduct);
router.delete('/products/:id', validate(idParamSchema, 'params'), controller.deleteProduct);
router.get('/reorder-rules', controller.listReorderRules);
router.post('/reorder-rules', validate(reorderRuleSchema), controller.createReorderRule);
router.put('/reorder-rules/:id', validate(idParamSchema, 'params'), validate(reorderRuleUpdateSchema), controller.updateReorderRule);
router.delete('/reorder-rules/:id', validate(idParamSchema, 'params'), controller.deleteReorderRule);
router.get('/warehouses', controller.listWarehouses);
router.post('/warehouses', validate(warehouseSchema), controller.createWarehouse);
router.put('/warehouses/:id', validate(idParamSchema, 'params'), validate(warehouseUpdateSchema), controller.updateWarehouse);
router.delete('/warehouses/:id', validate(idParamSchema, 'params'), controller.deleteWarehouse);
router.get('/warehouses/:id/locations', validate(idParamSchema, 'params'), controller.listLocations);
router.post('/locations', validate(locationSchema), controller.createLocation);
router.put('/locations/:id', validate(idParamSchema, 'params'), validate(locationUpdateSchema), controller.updateLocation);
router.delete('/locations/:id', validate(idParamSchema, 'params'), controller.deleteLocation);
export default router;
